#!/bin/bash

mkdir $1

cd $1

go mod init $1

FILE=$1.go

touch $FILE

echo """package main

import (
    \"advent/lib\"
)

func main() {
    lib.RunAndScore(\"Part 1\", p1)
    lib.RunAndScore(\"Part 2\", p2)
}

func p1() int {
    sum := 0

    return sum
}
func p2() int {
    sum := 0

    return sum
}""" > $FILE

cd ..

go work use $1

